[package]
name = "level35"
version = "0.0.1"
edition = "2024"

[dev-dependencies]
ethers-core = "2.0.14"
k256 = "0.13.4"
rand_core = { version = "0.9.3", features = ["os_rng"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
hex = "0.4.3"